const actionTypes = {
    MUTE_VOLUME: "MUTE_VOLUME",
    UNMUTE_VOLUME: "UNMUTE_VOLUME",

    OPEN_MENU: "OPEN_MENU",
    CLOSE_MENU: "CLOSE_MENU",

    ITEM_LOADING: "ITEM_LOADING",
    ITEM_LOADED: "ITEM_LOADED",
    ITEM_NOT_LOADED: "ITEM_NOT_LOADED",

    PREVIOUS_ITEM: "PREVIOUS_ITEM",
    NEXT_ITEM: "NEXT_ITEM",
    
    PAUSE_ITEM: "PAUSE_ITEM",
    PLAY_ITEM: "PLAY_ITEM",

    SELECT_ITEM: "SELECT_ITEM",
    PLAY_SELECTED: "PLAY_SELECTED",

};

export default actionTypes
